language: go
passThrough:
- function:
    package: github.com/modelcontextprotocol/go-sdk/mcp
    name: NewServer
    receiver: false
  copy:
  - from: arg(0)
    to: result
  - from: arg(1)
    to: result
- function:
    package: github.com/modelcontextprotocol/go-sdk/mcp
    name: AddTool
    receiver: false
  copy:
  - from: arg(1)
    to: arg(0)
  - from: arg(2)
    to: arg(0)
- function:
    package: github.com/modelcontextprotocol/go-sdk/mcp
    type: Server
    name: AddTool
    receiver: true
  copy:
  - from: arg(0)
    to: this
  - from: arg(1)
    to: this
- function:
    package: github.com/modelcontextprotocol/go-sdk/mcp
    type: Server
    name: AddPrompt
    receiver: true
  copy:
  - from: arg(0)
    to: this
  - from: arg(1)
    to: this
- function:
    package: github.com/modelcontextprotocol/go-sdk/mcp
    type: Server
    name: AddResource
    receiver: true
  copy:
  - from: arg(0)
    to: this
  - from: arg(1)
    to: this
- function:
    package: github.com/modelcontextprotocol/go-sdk/mcp
    type: Server
    name: AddResourceTemplate
    receiver: true
  copy:
  - from: arg(0)
    to: this
  - from: arg(1)
    to: this
- function:
    package: github.com/modelcontextprotocol/go-sdk/mcp
    type: Server
    name: AddSendingMiddleware
    receiver: true
  copy:
  - from: arg(0)
    to: this
- function:
    package: github.com/modelcontextprotocol/go-sdk/mcp
    type: Server
    name: AddReceivingMiddleware
    receiver: true
  copy:
  - from: arg(0)
    to: this
- function:
    package: github.com/modelcontextprotocol/go-sdk/mcp
    name: NewStreamableHTTPHandler
    receiver: false
  copy:
  - from: arg(0)
    to: result
  - from: arg(1)
    to: result
- function:
    package: github.com/modelcontextprotocol/go-sdk/mcp
    name: ResourceNotFoundError
    receiver: false
  copy:
  - from: arg(0)
    to: result
- function:
    package: github.com/modelcontextprotocol/go-sdk/mcp
    name: URLElicitationRequiredError
    receiver: false
  copy:
  - from: arg(0)
    to: result
