import MarkScan

#print axioms MarkScan.AlgorithmLemmas.iterC_inv
#print axioms MarkScan.AlgorithmLemmas.iterC_rounds_le
#print axioms MarkScan.AlgorithmLemmas.iterC_stable
#print axioms MarkScan.AlgorithmLemmas.iterC_rounds_le_measure
#print axioms MarkScan.AlgorithmLemmas.iterC_lockstep
#print axioms MarkScan.AlgorithmLemmas.mem_addNew
#print axioms MarkScan.AlgorithmLemmas.nodup_addNew
#print axioms MarkScan.AlgorithmLemmas.mem_dedup
#print axioms MarkScan.AlgorithmLemmas.nodup_dedup
#print axioms MarkScan.AlgorithmLemmas.filter_ne_length_lt
#print axioms MarkScan.AlgorithmLemmas.length_le_of_nodup_subset
#print axioms MarkScan.AlgorithmLemmas.length_dedup_le
#print axioms MarkScan.AlgorithmLemmas.filter_length_le_mono
#print axioms MarkScan.AlgorithmLemmas.filter_length_lt_mono
#print axioms MarkScan.AlgorithmLemmas.sum_map_le
#print axioms MarkScan.AlgorithmLemmas.sum_map_lt
#print axioms MarkScan.AlgorithmLemmas.sum_map_le_mul
#print axioms MarkScan.AlgorithmLemmas.all_false_wit
#print axioms MarkScan.AlgorithmLemmas.contains_iff
#print axioms MarkScan.AlgorithmLemmas.not_contains_iff
#print axioms MarkScan.AlgorithmLemmas.not_contains_false
#print axioms MarkScan.Algorithm.Reaches.tail
#print axioms MarkScan.Algorithm.Reaches.nodes
#print axioms MarkScan.Algorithm.mem_reachStep
#print axioms MarkScan.Algorithm.reachList_reaches
#print axioms MarkScan.Algorithm.reachList_closed
#print axioms MarkScan.Algorithm.mem_reachList
#print axioms MarkScan.Algorithm.mem_nodeSites
#print axioms MarkScan.AlgorithmLemmas.find_witness
#print axioms MarkScan.AlgorithmLemmas.lookup_map_self
#print axioms MarkScan.AlgorithmLemmas.mem_refU
#print axioms MarkScan.AlgorithmLemmas.refCubeOk_iff
#print axioms MarkScan.AlgorithmLemmas.mem_refGens
#print axioms MarkScan.AlgorithmLemmas.mem_refRound
#print axioms MarkScan.AlgorithmLemmas.refStable_iff
#print axioms MarkScan.AlgorithmLemmas.refGens_universe
#print axioms MarkScan.AlgorithmLemmas.refMeasure_dec
#print axioms MarkScan.AlgorithmLemmas.refFinal_stable
#print axioms MarkScan.AlgorithmLemmas.refGens_sound
#print axioms MarkScan.AlgorithmLemmas.refFinal_sound
#print axioms MarkScan.AlgorithmLemmas.refFinal_complete
#print axioms MarkScan.AlgorithmLemmas.refFinal_iff
#print axioms MarkScan.AlgorithmLemmas.refCubeSat_iff
#print axioms MarkScan.AlgorithmLemmas.applicableOn_iff
#print axioms MarkScan.AlgorithmLemmas.mem_appSites
#print axioms MarkScan.AlgorithmLemmas.applicable_node
#print axioms MarkScan.AlgorithmLemmas.mem_needSeeds
#print axioms MarkScan.AlgorithmLemmas.mem_needGens
#print axioms MarkScan.AlgorithmLemmas.mem_needStep
#print axioms MarkScan.AlgorithmLemmas.neededSet_stable
#print axioms MarkScan.AlgorithmLemmas.neededSet_iff
#print axioms MarkScan.AlgorithmLemmas.mem_appSites_applicable
#print axioms MarkScan.refInS_iff
#print axioms MarkScan.refApplicable_iff
#print axioms MarkScan.refNeeded_iff
#print axioms MarkScan.refFuel_suffices
#print axioms MarkScan.AlgorithmLemmas.bool_eq_of_iff
#print axioms MarkScan.AlgorithmLemmas.singleSat_iff
#print axioms MarkScan.AlgorithmLemmas.joinedSat_iff
#print axioms MarkScan.AlgorithmLemmas.mem_sigGens
#print axioms MarkScan.AlgorithmLemmas.mem_nodeSigs
#print axioms MarkScan.AlgorithmLemmas.mem_rootSigs
#print axioms MarkScan.AlgorithmLemmas.mem_joinedGensAt
#print axioms MarkScan.AlgorithmLemmas.mem_reachAll
#print axioms MarkScan.AlgorithmLemmas.mem_optGens
#print axioms MarkScan.AlgorithmLemmas.mem_refU_congr
#print axioms MarkScan.AlgorithmLemmas.mem_refGens_congr
#print axioms MarkScan.AlgorithmLemmas.opt_ref_lockstep
#print axioms MarkScan.AlgorithmLemmas.lookup_map_congr
#print axioms MarkScan.AlgorithmLemmas.refCubeSat_congr
#print axioms MarkScan.opt_eq_ref
#print axioms MarkScan.optInS_eq
#print axioms MarkScan.optApplicable_eq
#print axioms MarkScan.optNeeded_eq
#print axioms MarkScan.optInS_iff
#print axioms MarkScan.optApplicable_iff
#print axioms MarkScan.optNeeded_iff
#print axioms MarkScan.closure_sig_congr
#print axioms MarkScan.closure_dedup
#print axioms MarkScan.AlgorithmLemmas.le_foldl_max
#print axioms MarkScan.AlgorithmLemmas.foldl_max_le
#print axioms MarkScan.AlgorithmLemmas.sum_map_mul_right
#print axioms MarkScan.AlgorithmLemmas.le_sum_map_of_mem
#print axioms MarkScan.AlgorithmLemmas.mul_le_sum_map
#print axioms MarkScan.AlgorithmLemmas.sig_le_maxCond
#print axioms MarkScan.AlgorithmLemmas.mem_allSigs
#print axioms MarkScan.AlgorithmLemmas.reachAll_nodes
#print axioms MarkScan.AlgorithmLemmas.rootSigs_cost_le
#print axioms MarkScan.AlgorithmLemmas.joinedSigs_cost_le
#print axioms MarkScan.refSteps_eq
#print axioms MarkScan.optRoundCost_le
#print axioms MarkScan.optSteps_le
#print axioms MarkScan.AlgorithmLemmas.fam_sites
#print axioms MarkScan.AlgorithmLemmas.fam_nodeSites
#print axioms MarkScan.AlgorithmLemmas.fam_wf
#print axioms MarkScan.AlgorithmLemmas.length_flatMap_one
#print axioms MarkScan.AlgorithmLemmas.filter_length_zero
#print axioms MarkScan.AlgorithmLemmas.fam_roots_length
#print axioms MarkScan.AlgorithmLemmas.fam_root_cost
#print axioms MarkScan.fam_ref_round_ge
#print axioms MarkScan.fam_opt_round_le
#print axioms MarkScan.fam_speedup
#print axioms MarkScan.CoarseningLemmas.hom_callees
#print axioms MarkScan.CoarseningLemmas.hom_nodeSites
#print axioms MarkScan.CoarseningLemmas.nodeSites_sites
#print axioms MarkScan.CoarseningLemmas.reaches_closed
#print axioms MarkScan.merge_hom
#print axioms MarkScan.reaches_hom
#print axioms MarkScan.inS_hom
#print axioms MarkScan.cubeSat_hom
#print axioms MarkScan.applicable_hom
#print axioms MarkScan.needed_hom
#print axioms MarkScan.applicable_stmtApplicable
#print axioms MarkScan.keyed_overapprox
#print axioms MarkScan.coarse_keyed_overapprox
#print axioms MarkScan.coarse_needed_overapprox
#print axioms MarkScan.CoarseningExample.sinkSite_cond
#print axioms MarkScan.CoarseningExample.hM_fib
#print axioms MarkScan.CoarseningExample.coarse_hom
#print axioms MarkScan.CoarseningExample.fine_callees
#print axioms MarkScan.CoarseningExample.fine_reach_from_1
#print axioms MarkScan.CoarseningExample.fine_reach_from_2
#print axioms MarkScan.CoarseningExample.fine_gens_from_1
#print axioms MarkScan.CoarseningExample.fine_not_inS_1_7
#print axioms MarkScan.CoarseningExample.fine_not_applicable
#print axioms MarkScan.CoarseningExample.coarse_inS_2_7
#print axioms MarkScan.CoarseningExample.coarse_reach_2_5
#print axioms MarkScan.CoarseningExample.coarse_applicable
#print axioms MarkScan.coarsening_loses_precision
#print axioms MarkScan.CollapseLemmas.dnf_sat_iff
#print axioms MarkScan.CollapseLemmas.dnf_sat_mono
#print axioms MarkScan.CollapseLemmas.subset_refl
#print axioms MarkScan.CollapseLemmas.subset_trans
#print axioms MarkScan.CollapseLemmas.filter_length_le_of_imp
#print axioms MarkScan.CollapseLemmas.filter_length_lt_of_imp
#print axioms MarkScan.CollapseLemmas.mem_satGens
#print axioms MarkScan.CollapseLemmas.mem_newGens
#print axioms MarkScan.CollapseLemmas.mem_allGens
#print axioms MarkScan.CollapseLemmas.filter_nil_of_false
#print axioms MarkScan.CollapseLemmas.newGens_nil_iff
#print axioms MarkScan.CollapseLemmas.missing_le
#print axioms MarkScan.CollapseLemmas.missing_lt
#print axioms MarkScan.CollapseLemmas.closeLoop_of_nil
#print axioms MarkScan.CollapseLemmas.closeLoop_step
#print axioms MarkScan.CollapseLemmas.closeLoop_fix
#print axioms MarkScan.CollapseLemmas.closeLoop_fuel_irrel
#print axioms MarkScan.CollapseLemmas.closeLoop_extensive
#print axioms MarkScan.CollapseLemmas.closeLoop_induction
#print axioms MarkScan.closure_extensive
#print axioms MarkScan.closure_closed
#print axioms MarkScan.closure_fuel_enough
#print axioms MarkScan.closure_induction
#print axioms MarkScan.closure_least
#print axioms MarkScan.closure_mono
#print axioms MarkScan.closure_of_closed
#print axioms MarkScan.closure_idem
#print axioms MarkScan.wfb_iff
#print axioms MarkScan.CollapseLemmas.reaches_trans
#print axioms MarkScan.CollapseLemmas.reaches_snoc
#print axioms MarkScan.CollapseLemmas.reaches_nodes
#print axioms MarkScan.CollapseLemmas.reachSite_sat
#print axioms MarkScan.mem_reachList
#print axioms MarkScan.self_mem_reachList
#print axioms MarkScan.CollapseLemmas.mem_reachSites
#print axioms MarkScan.CollapseLemmas.nodeAbsSites_sub_reachSites
#print axioms MarkScan.CollapseLemmas.reachSites_mono
#print axioms MarkScan.collapse_is_solution
#print axioms MarkScan.CollapseLemmas.solution_closed_reach
#print axioms MarkScan.collapse_least
#print axioms MarkScan.collapse_context_tree_node
#print axioms MarkScan.collapse_context_tree
#print axioms MarkScan.CollapseLemmas.mem_nodeSites
#print axioms MarkScan.CollapseLemmas.abstract_mem_nodeAbsSites
#print axioms MarkScan.inS_iff_closure
#print axioms MarkScan.CollapseLemmas.ctxLoop_inner
#print axioms MarkScan.CollapseLemmas.feedIn_inner
#print axioms MarkScan.conceptContexts_collapse
#print axioms MarkScan.conceptContexts_inputs
#print axioms MarkScan.feedIn_collapse
#print axioms MarkScan.CondLemmas.dnf_sat_iff
#print axioms MarkScan.CondLemmas.dnf_sat_append
#print axioms MarkScan.CondLemmas.bool_eq_of_iff
#print axioms MarkScan.CondLemmas.dnf_sat_product
#print axioms MarkScan.CondLemmas.any_isEmpty_iff
#print axioms MarkScan.CondLemmas.sat_singletons_iff
#print axioms MarkScan.CondLemmas.sat_unit
#print axioms MarkScan.Cond.sat_toDnf
#print axioms MarkScan.Dnf.sat_mono
#print axioms MarkScan.Cond.sat_mono
#print axioms MarkScan.Dnf.relax_sat_iff
#print axioms MarkScan.Dnf.relax_sound
#print axioms MarkScan.Dnf.relax_cubes_small
#print axioms MarkScan.Dnf.relax_union
#print axioms MarkScan.Dnf.sat_not_join_distributive
#print axioms MarkScan.naiveAny_unsound
#print axioms MarkScan.naiveAny_sound_of_no_empty_cube
#print axioms MarkScan.relax_precision_loss
#print axioms MarkScan.ECube.abstract_sound
#print axioms MarkScan.ECube.positive_ignores_negated
#print axioms MarkScan.erasure_precision_loss
#print axioms MarkScan.andOrChain_toDnf_length
#print axioms MarkScan.andOrChain_size
#print axioms MarkScan.tree_vs_dnf_cost
#print axioms MarkScan.EngineSoundnessLemmas.mem_callees
#print axioms MarkScan.EngineSoundnessLemmas.mem_nodeSites
#print axioms MarkScan.EngineSoundnessLemmas.site_pc
#print axioms MarkScan.EngineSoundnessLemmas.cube_mem
#print axioms MarkScan.EngineSoundnessLemmas.gen_mem
#print axioms MarkScan.EngineSoundnessLemmas.list_choice
#print axioms MarkScan.Reaches.trans
#print axioms MarkScan.Reaches.callee
#print axioms MarkScan.pe_zero_ctx
#print axioms MarkScan.pe_sound
#print axioms MarkScan.ecube_applicable
#print axioms MarkScan.fires_applicable
#print axioms MarkScan.pcwf_needed
#print axioms MarkScan.EngineSoundnessLemmas.d1_calls
#print axioms MarkScan.EngineSoundnessLemmas.d1_reaches
#print axioms MarkScan.EngineSoundnessLemmas.d1_noJoin_inv
#print axioms MarkScan.d1Program_wf
#print axioms MarkScan.d1_fires
#print axioms MarkScan.d1_not_applicableNoJoin
#print axioms MarkScan.d1_applicable
#print axioms MarkScan.EngineSoundnessLemmas.pw_calls
#print axioms MarkScan.EngineSoundnessLemmas.pw_sites1
#print axioms MarkScan.EngineSoundnessLemmas.pw_inv
#print axioms MarkScan.pwProgram_wf
#print axioms MarkScan.pw_applicable
#print axioms MarkScan.pw_not_fires
#print axioms MarkScan.FlowSensitiveLemmas.ptreach_root
#print axioms MarkScan.FlowSensitiveLemmas.ptreach_entry
#print axioms MarkScan.FlowSensitiveLemmas.infs_ptreach
#print axioms MarkScan.FlowSensitiveLemmas.reaches_snoc
#print axioms MarkScan.FlowSensitiveLemmas.ptreach_reaches
#print axioms MarkScan.FlowSensitiveLemmas.abs_mem
#print axioms MarkScan.FlowSensitiveLemmas.gen_mem
#print axioms MarkScan.FlowSensitiveLemmas.nodeSites_mem
#print axioms MarkScan.FlowSensitiveLemmas.choose_fin
#print axioms MarkScan.FlowSensitiveLemmas.sound_aux
#print axioms MarkScan.pe_ptreach
#print axioms MarkScan.fs_sound
#print axioms MarkScan.FlowSensitiveLemmas.exCtx_ptreach
#print axioms MarkScan.FlowSensitiveLemmas.exCtx_infs
#print axioms MarkScan.fs_ctx_needed
#print axioms MarkScan.fs_fires_applicable
#print axioms MarkScan.fs_refines_fi
#print axioms MarkScan.applicableFS_implies_applicable
#print axioms MarkScan.FlowSensitiveLemmas.sink_cond
#print axioms MarkScan.FlowSensitiveLemmas.sink_gens
#print axioms MarkScan.FlowSensitiveLemmas.src_cond
#print axioms MarkScan.FlowSensitiveLemmas.src_gens
#print axioms MarkScan.FlowSensitiveLemmas.exOrder_wf
#print axioms MarkScan.FlowSensitiveLemmas.exOrder_inv
#print axioms MarkScan.fs_strict
#print axioms MarkScan.FlowSensitiveLemmas.exLoop_lin_inv
#print axioms MarkScan.linear_order_unsound
#print axioms MarkScan.exLoop_fs_applicable
#print axioms MarkScan.FlowSensitiveLemmas.sum_const_map
#print axioms MarkScan.fsPoints_length
#print axioms MarkScan.mem_fsPoints
#print axioms MarkScan.markset_exact
#print axioms MarkScan.markset_exact_coarse
#print axioms MarkScan.pe_mono
#print axioms MarkScan.SelectionLemmas.ecube_mono
#print axioms MarkScan.fires_mono
#print axioms MarkScan.pe_zero_reach
#print axioms MarkScan.SelectionLemmas.atom_of_pos
#print axioms MarkScan.SelectionLemmas.gen_of_assign
#print axioms MarkScan.SelectionLemmas.choose_ctx
#print axioms MarkScan.SelectionLemmas.site_ofScan
#print axioms MarkScan.SelectionLemmas.ofScan_le_all
#print axioms MarkScan.sel_pe_iff
#print axioms MarkScan.sel_fires_iff
#print axioms MarkScan.rel_preserves_needed_strong
#print axioms MarkScan.rel_preserves_needed
#print axioms MarkScan.rel_fires_iff
#print axioms MarkScan.rel_sound_subset
#print axioms MarkScan.SelectionLemmas.cex_pos_tr
#print axioms MarkScan.SelectionLemmas.cex_pos_sink
#print axioms MarkScan.SelectionLemmas.cex_no_fact
#print axioms MarkScan.SelectionLemmas.cex_src_mem
#print axioms MarkScan.SelectionLemmas.cex_tr_mem
#print axioms MarkScan.SelectionLemmas.cex_sink_mem
#print axioms MarkScan.SelectionLemmas.cex_abs_src_cond
#print axioms MarkScan.SelectionLemmas.cex_abs_src_gens
#print axioms MarkScan.SelectionLemmas.cex_abs_tr_cond
#print axioms MarkScan.SelectionLemmas.cex_abs_tr_gens
#print axioms MarkScan.SelectionLemmas.cex_abs_sink_cond
#print axioms MarkScan.SelectionLemmas.cex_InS1
#print axioms MarkScan.SelectionLemmas.cex_InS2
#print axioms MarkScan.SelectionLemmas.cex_app_tr
#print axioms MarkScan.SelectionLemmas.cex_app_sink
#print axioms MarkScan.cex_needed_one
#print axioms MarkScan.SelectionLemmas.cex_no_fires
#print axioms MarkScan.SelectionLemmas.cex_baseline_fires
#print axioms MarkScan.backward_closure_necessary
#print axioms MarkScan.needSinkOnly_unsound
