language: java
library: org.yaml:snakeyaml:2.2
passThrough:
- function: org.yaml.snakeyaml.Yaml#loadAs
  copy:
  - from: arg(0)
    to: result
  - from:
    - arg(0)
    - .java.lang.String#<serialized-value>#java.lang.Object
    to: result
- function: org.yaml.snakeyaml.Yaml#load
  copy:
  - from: arg(0)
    to: result
  - from:
    - arg(0)
    - .java.lang.String#<serialized-value>#java.lang.Object
    to: result
- function: org.yaml.snakeyaml.Yaml#loadAll
  copy:
  - from: arg(0)
    to:
    - result
    - .java.lang.Iterable#Element#java.lang.Object
  - from:
    - arg(0)
    - .java.lang.String#<serialized-value>#java.lang.Object
    to:
    - result
    - .java.lang.Iterable#Element#java.lang.Object
- function: org.yaml.snakeyaml.Yaml#dump
  copy:
  - from: arg(0)
    to: result
  - from: arg(0)
    to:
    - this
    - .org.yaml.snakeyaml.Yaml#<serialized-value>#java.lang.Object
- function: org.yaml.snakeyaml.Yaml#dumpAs
  copy:
  - from: arg(0)
    to: result
  - from: arg(0)
    to:
    - this
    - .org.yaml.snakeyaml.Yaml#<serialized-value>#java.lang.Object
- function: org.yaml.snakeyaml.Yaml#dumpAsMap
  copy:
  - from: arg(0)
    to: result
  - from: arg(0)
    to:
    - this
    - .org.yaml.snakeyaml.Yaml#<serialized-value>#java.lang.Object
- function: org.yaml.snakeyaml.Yaml#dumpAll
  copy:
  - from:
    - arg(0)
    - .java.util.Iterator#Element#java.lang.Object
    to: result
  - from: arg(0)
    to: result
  - from: arg(0)
    to:
    - this
    - .org.yaml.snakeyaml.Yaml#<serialized-value>#java.lang.Object
- function: org.yaml.snakeyaml.Yaml#serialize
  copy:
  - from: arg(0)
    to: result
  - from: arg(0)
    to:
    - this
    - .org.yaml.snakeyaml.Yaml#<serialized-value>#java.lang.Object
- function: org.yaml.snakeyaml.Yaml#load
  copy:
  - from:
    - this
    - .org.yaml.snakeyaml.Yaml#<serialized-value>#java.lang.Object
    to: result
- function: org.yaml.snakeyaml.Yaml#loadAs
  copy:
  - from:
    - this
    - .org.yaml.snakeyaml.Yaml#<serialized-value>#java.lang.Object
    to: result
- function: org.yaml.snakeyaml.Yaml#loadAll
  copy:
  - from:
    - this
    - .org.yaml.snakeyaml.Yaml#<serialized-value>#java.lang.Object
    to:
    - result
    - .java.lang.Iterable#Element#java.lang.Object
