language: java
library: org.mybatis:mybatis-spring:3.0.5
dependencies:
- org.apache.ibatis:ibatis-core:3.0
- org.springframework:spring-tx:6.1.5
passThrough:
- function: org.mybatis.spring.support.SqlSessionDaoSupport#setSqlSessionTemplate
  copy:
  - from: arg(0)
    to:
    - this
    - .org.mybatis.spring.support.SqlSessionDaoSupport#content#java.lang.Object
- function: org.mybatis.spring.support.SqlSessionDaoSupport#setSqlSessionFactory
  copy:
  - from: arg(0)
    to:
    - this
    - .org.mybatis.spring.support.SqlSessionDaoSupport#content#java.lang.Object
- function: org.mybatis.spring.support.SqlSessionDaoSupport#setSqlSessionFactory
  signature:
    params:
    - index: 0
      type: org.apache.ibatis.session.SqlSessionFactory
  copy:
  - from: arg(0)
    to:
    - this
    - .org.mybatis.spring.support.SqlSessionDaoSupport#sqlSessionFactory#java.lang.Object
- function: org.mybatis.spring.support.SqlSessionDaoSupport#getSqlSession
  copy:
  - from:
    - this
    - .org.mybatis.spring.support.SqlSessionDaoSupport#content#java.lang.Object
    to: result
- function: org.mybatis.spring.support.SqlSessionDaoSupport#setSqlSessionTemplate
  signature:
    params:
    - index: 0
      type: org.mybatis.spring.SqlSessionTemplate
  copy:
  - from: arg(0)
    to:
    - this
    - .org.mybatis.spring.support.SqlSessionDaoSupport#sqlSessionTemplate#java.lang.Object
