language: java
library: org.apache.wicket:wicket:1.4.23
passThrough:
- function: org.apache.wicket.Component#setComponentBorder
  copy:
  - from:
    - this
    - .org.apache.wicket.Component#componentBorder#java.lang.Object
    to: result
  - from:
    - this
    - .org.apache.wicket.Component#componentBorder#java.lang.Object
    to: result
  - from: this
    to: result
- function: org.apache.wicket.PageParameters#toRequestParameters
  copy:
  - from: this
    to: result
- function: org.apache.wicket.Component#locateMarkupStream
  copy:
  - from:
    - this
    - .org.apache.wicket.Component#markupStream#java.lang.Object
    to: result
  - from:
    - this
    - .org.apache.wicket.Component#markupStream#java.lang.Object
    to: result
  - from:
    - this
    - .org.apache.wicket.Component#markupStream#java.lang.Object
    to: result
  - from:
    - this
    - .org.apache.wicket.Component#markupStream#java.lang.Object
    to: result
  - from: this
    to: result
- function: org.apache.wicket.Component#setMarkupStream
  copy:
  - from:
    - this
    - .org.apache.wicket.Component#markupStream#java.lang.Object
    to: result
  - from:
    - this
    - .org.apache.wicket.Component#markupStream#java.lang.Object
    to: result
  - from: this
    to: result
- function: org.apache.wicket.Component#findMarkupStream
  copy:
  - from:
    - this
    - .org.apache.wicket.Component#markupStream#java.lang.Object
    to: result
  - from:
    - this
    - .org.apache.wicket.Component#markupStream#java.lang.Object
    to: result
  - from: this
    to: result
- function: org.apache.wicket.Response#encodeURL
  copy:
  - from: arg(0)
    to: result
