passThrough:
- function: org.springframework.jdbc.core.namedparam.NamedParameterUtils#parseSqlStatement
  copy:
  - from: arg(0)
    to: result
- function: org.springframework.jdbc.core.namedparam.NamedParameterUtils#substituteNamedParameters
  copy:
  - from: arg(0)
    to: result
- function: org.springframework.jdbc.core.namedparam.NamedParameterUtils#parseSqlStatementIntoString
  copy:
  - from: arg(0)
    to: result
