#!/usr/bin/env bash
# Regenerates MAP.md: every Lean file, the source file it models, and the theorems it gates.
#
# Generated, not hand-written, so the index cannot drift from the tree.  `check-map.sh` fails if
# MAP.md differs from this script's output.  The "gates" column lists the names put through
# `#constructive` -- the headline results, as opposed to the lemmas that support them.

set -uo pipefail
cd "$(dirname "$0")" || exit 2
repo_root="$(cd .. && pwd)"
# shellcheck source=counterpart.sh
. ./counterpart.sh

gates() {
  # `#constructive a b c` may list several names, and a file may have several such lines.
  sed -n 's/^#constructive[[:space:]]*//p' "$1" | tr -s ' ' '\n' | sed '/^$/d' \
    | sed 's/^/`/; s/$/`/' | paste -sd' ' -
}

cat <<'HEADER'
# What is proved about what

Generated by `./gen-map.sh` — do not edit. `check-map.sh` fails if this file is stale.

The index to the golden model: each row is one Lean file, the source file it mirrors (the mapping
law is in `README.md`), and the headline theorems it gates through `#constructive`. Supporting
lemmas are not listed; read the file.

HEADER

emit_group() {
  local title="$1"; shift
  local files=("$@")
  [[ ${#files[@]} -eq 0 ]] && return
  printf '## %s\n\n' "$title"
  printf '| Lean | Source counterpart | gates |\n|---|---|---|\n'
  local f rel src g
  for f in "${files[@]}"; do
    rel="${f#Opentaint/}"
    src="$(counterpart_for "$rel" "$repo_root")"
    g="$(gates "$f")"
    printf '| `%s` | %s | %s |\n' "$f" "${src:+\`${src}\`}" "${g:-—}"
  done
  printf '\n'
}

mapfile -t support < <(find Opentaint/Support -name '*.lean' 2>/dev/null | sort)
mapfile -t mirrored < <(find Opentaint -name '*.lean' -not -path 'Opentaint/Support/*' | sort \
  | grep -vxF -f <(grep -vE '^\s*(#|$)' LEGACY.txt) 2>/dev/null || true)
mapfile -t legacy < <(grep -vE '^\s*(#|$)' LEGACY.txt 2>/dev/null | sort)

emit_group "The mirrored tree" "${mirrored[@]}"
emit_group "Support (no source counterpart)" "${support[@]}"

if [[ ${#legacy[@]} -gt 0 ]]; then
  printf '## Awaiting a home\n\n'
  printf 'Listed in `LEGACY.txt`: modeled, proved, but not yet moved onto the mirrored tree. The\n'
  printf 'restructure is finished when this section is gone.\n\n'
  printf '| Lean | gates |\n|---|---|\n'
  for f in "${legacy[@]}"; do
    printf '| `%s` | %s |\n' "$f" "$(gates "$f" || true)"
  done
  printf '\n'
fi
