package approximation

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v2"
)

const descriptorHeader = "# Generated by 'opentaint compile approximations'. Do not edit.\n"

// descriptor identifies the source and dependencies of a model build.
type descriptor struct {
	// SourceProject is the project that supplied the models.
	SourceProject string `yaml:"sourceProject"`
	// Dependencies are the libraries used to compile the models.
	Dependencies []string `yaml:"dependencies"`
}

func writeDescriptor(outputDir string, d descriptor) error {
	if d.Dependencies == nil {
		d.Dependencies = []string{}
	}
	body, err := yaml.Marshal(d)
	if err != nil {
		return fmt.Errorf("failed to render the approximation descriptor: %w", err)
	}
	path := filepath.Join(outputDir, descriptorName)
	if err := os.WriteFile(path, append([]byte(descriptorHeader), body...), 0o644); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}
	return nil
}
