passThrough:
- function:
    package: compress/lzw
    name: NewReader
    receiver: false
  copy:
  - from: arg(0)
    to: result
- function:
    package: compress/lzw
    name: NewWriter
    receiver: false
  copy:
  - from: result
    to: arg(0)
