passThrough:
- function:
    package: gopkg.in/yaml
    name: Marshal
    receiver: false
  copy:
  - from: arg(0)
    to: result(0)
- function:
    package: gopkg.in/yaml
    name: Unmarshal
    receiver: false
  copy:
  - from: arg(0)
    to: arg(1)
- function:
    package: gopkg.in/yaml
    name: UnmarshalStrict
    receiver: false
  copy:
  - from: arg(0)
    to: arg(1)
- function:
    package: gopkg.in/yaml
    name: NewDecoder
    receiver: false
  copy:
  - from: arg(0)
    to: result
- function:
    package: gopkg.in/yaml
    type: Decoder
    name: Decode
    receiver: true
  copy:
  - from: this
    to: arg(0)
- function:
    package: gopkg.in/yaml
    type: Encoder
    name: Encode
    receiver: true
  copy:
  - from: arg(0)
    to: this
- function:
    package: gopkg.in/yaml
    type: Node
    name: Decode
    receiver: true
  copy:
  - from: this
    to: arg(0)
- function:
    package: gopkg.in/yaml
    type: Node
    name: Encode
    receiver: true
  copy:
  - from: arg(0)
    to: this
- function:
    package: gopkg.in/yaml
    type: Node
    name: SetString
    receiver: true
  copy:
  - from: arg(0)
    to: this
- function:
    package: gopkg.in/yaml
    name: NewEncoder
    receiver: false
  copy:
  - from: result
    to: arg(0)
