language: java
passThrough:
- function: java.lang.ref.Reference#get
  signature: () java.lang.Object
  copy:
  - from: this
    to: result
  - from:
    - this
    - .java.lang.ref.Reference#content#java.lang.Object
    to: result
- function: java.lang.ref.Reference#<init>
  signature: (java.lang.Object) void
  copy:
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .java.lang.ref.Reference#content#java.lang.Object
- function: java.lang.ref.Reference#<init>
  signature: (java.lang.Object, java.lang.ref.ReferenceQueue) void
  copy:
  - from: arg(0)
    to: this
  - from: arg(0)
    to:
    - this
    - .java.lang.ref.Reference#content#java.lang.Object
- function: java.lang.ref.Reference#get
  signature: () java.lang.Object
  taintCopyOnly: true
  copy:
  - from: this
    to: result
