language: java
passThrough:
- function: java.lang.ref.Reference#get
  signature: () java.lang.Object
  copy:
  - from: this
    to: result
- function: java.lang.ref.Reference#<init>
  signature: (java.lang.Object) void
  copy:
  - from: arg(0)
    to: this
- function: java.lang.ref.Reference#<init>
  signature: (java.lang.Object, java.lang.ref.ReferenceQueue) void
  copy:
  - from: arg(0)
    to: this
- function: java.lang.ref.Reference#get
  signature: () java.lang.Object
  taintCopyOnly: true
  copy:
  - from: this
    to: result
